Working on converting from make to bash

diff --git a/bin/mtechdocs b/bin/mtechdocs
--- a/bin/mtechdocs
+++ b/bin/mtechdocs
@@ -38,8 +38,8 @@ export GREEN='\033[0;32m'
 export YELLOW='\033[1;33m'
 export NC='\033[0m'
 
-# The pandoc filter list
-FILTERS="-F $MKTECHDOCSHOME/bin/flt-include.py -F $MKTECHDOCSHOME/bin/flt-comment-block.py -F $MKTECHDOCSHOME/bin/flt-comment.py -F $MKTECHDOCSHOME/bin/flt-plantuml.py -M umlformat=svg -F $MKTECHDOCSHOME/bin/flt-notetip.py -F $MKTECHDOCSHOME/bin/flt-include-code.py"
+TEXLISTINGS=$MKTECHDOCSHOME/lib/listings.tex
+TEXTEMPLATE=$MKTECHDOCSHOME/lib/template.tex
 
 #############################################################################
 # FUNCTIONS
@@ -55,10 +55,11 @@ function clog {
   COL=
   TYPEOUT=
   case "$TYPE" in
-    #INFO)
-    #  COL=$GREEN
-    #  TYPEOUT="[INFO]"
-    #  ;;
+    INFO)
+      COL=$GREEN
+      TYPEOUT="[+]"
+      MSG=" $MSG"
+      ;;
     ERROR)
       COL=$RED
       TYPEOUT="[ERROR]"
@@ -78,21 +79,26 @@ function clog {
 # Checks build environment and exits if something isn't right.
 #
 function check_build_env {
-  # Java 8
+  # Master document
+  if [[ ! -r "master.md" ]] ; then
+    clog ERROR "Cannot find master document master.md"
+    exit 1
+  fi
 
+  # Java 8
   if [[ $(java -version 2>&1 | grep 1.8) == "" ]] ; then
-  	clog ERROR "Can't find Java 8 (1.8)."
-  	exit 1
+    clog ERROR "Can't find Java 8 (1.8)."
+    exit 1
   fi
 
   # Executables
 
   #for exe in pandoc pd groovyc cg gtp flt_get_includes.groovy plantuml xelatex ; do
   for exe in pandoc flt-get-includes.py plantuml xelatex ; do
-  	if [[ $(which $exe) == "" ]] ; then
+    if [[ $(which $exe) == "" ]] ; then
       clog ERROR "Can't find $exe. Did you add $MKTECHDOCSHOME/bin to your PATH? Did you install all the dependencies?"
-  		exit 1
-  	fi
+      exit 1
+    fi
   done
 
   clog INFO "Build environment looks good."
@@ -125,17 +131,6 @@ function confirm {
 # Creates and populates a new project
 #
 function create_new_project {
-  DIR=$1
-
-  if [[ -d $DIR ]] ; then
-    clog ERROR "$DIR already exists. Giving up."
-    exit 1
-  fi
-
-  mkdir -p $DIR
-
-  pushd $DIR 1>/dev/null 2>&1
-
   clog INFO "Generating master.md"
 
   cat <<EOF > master.md
@@ -157,7 +152,30 @@ EOF
 My markup goes here.
 EOF
 
-  popd
+  clog INFO "Copying default configuration options into mktechdocs.conf."
+  cp $MKTECHDOCSHOME/lib/conf ./mktechdocs.conf
+  normal_exit $?
+}
+
+function cleanup {
+  # Clean up all the temporary build files unless keep is specified
+  if [[ "$KEEP_TEMP_FILES" != "true" ]] ; then
+    clog INFO "Removing old temporary build files"
+    
+    ls *.pyt 2>/dev/null | sed 's/\.pyt//' | while read template ; do
+      rm -f $template.md
+    done
+    
+    ls *.gt 2>/dev/null | sed 's/\.gt//' | while read template ; do
+      rm -f $template.md
+    done
+
+    ls *.htmlt 2>/dev/null | sed 's/\.htmlt//' | while read template ; do
+      rm -f $template.html
+    done
+
+    rm -f plantuml-*.uml plantuml-*.eps plantuml-*.svg $OUTPUT_FILE_NAME_BASE_ARG.pyt $OUTPUT_FILE_NAME_BASE_ARG.tex $OUTPUT_FILE_NAME_BASE_ARG.aux $OUTPUT_FILE_NAME_BASE_ARG.log $OUTPUT_FILE_NAME_BASE_ARG.toc $OUTPUT_FILE_NAME_BASE_ARG.out xelatex*.out
+  fi
 }
 
 #############################################################################
@@ -165,8 +183,28 @@ EOF
 #############################################################################
 
 # We need a project directory and configuration file
-PROJECT_DIR=$1
-CFG=$2
+CFG=$1
+PROJECT_DIR=$2
+
+if [[ "$CFG" == "init" ]] ; then
+  PROJECT_DIR=.
+  if confirm "Create and initialize new MkTechDocs project in the current directory?" ; then
+    clog INFO "Creating new project in $PROJECT_DIR"
+    create_new_project $PROJECT_DIR
+    exit 0
+  else
+    clog INFO "Goodbye"
+    exit 0
+  fi
+fi
+
+if [[ "$PROJECT_DIR" == "" ]] ; then
+  PROJECT_DIR=.
+fi
+
+if [[ "$CFG" == "" ]] ; then
+  CFG=mktechdocs.conf
+fi
 
 if [[ ! -r $CFG ]] ; then
   clog ERROR "Can't find configuration file '$CFG'"
@@ -175,12 +213,6 @@ fi
 
 if [[ ! -d $PROJECT_DIR ]] ; then
   clog ERROR "Can't find specified project path '$PROJECT_DIR'"
-  if confirm "Create and initialize new MkTechDocs project in $PROJECT_DIR?" ; then
-    clog INFO "Creating new project $PROJECT_DIR"
-    create_new_project $PROJECT_DIR
-  else
-    clog INFO "Goodbye"
-  fi
   exit 1
 fi
 
@@ -191,44 +223,205 @@ check_build_env
 pushd $PROJECT_DIR 1>/dev/null 2>&1
 normal_exit $?
 
-# First, we render all templates in the current directory
-ls *.pyt | sed 's/\.pyt//' | while read template ; do
-  clog INFO "building $template.md"
-  $template.renderer $template.pyt > $template.md
-done
+# Source our configuration file
+. $CFG
 
-ls *.htmlt | sed 's/\.htmlt//' | while read template ; do
-  clog INFO "building $template.html"
-  $template.renderer $template.htmlt > $template.html
+# Clean up old, possibly failed builds
+cleanup
+
+# Run any pre-build jobs
+if [[ "$BUILD_SCRIPT" != "" ]] ; then
+  if [[ -e $BUILD_SCRIPT ]] ; then
+    clog INFO "Running pre-build job $BUILD_SCRIPT"
+    $BUILD_SCRIPT pre
+  else
+    clog ERROR "$BUILD_SCRIPT is not executable. Giving up."
+    exit 1
+  fi
+fi
+
+# Render all templates (if we have any) in the current directory
+N=$(ls | grep -c *.pyt)
+if [[ "$N" != "0" ]] ; then
+  ls *.pyt | sed 's/\.pyt//' | while read template ; do
+    clog INFO "Rendering $template.pyt => $template.md"
+    $template.renderer $template.pyt > $template.md
+    normal_exit $?
+  done
+  [[ $? != 0 ]] && exit $?
+fi
+
+N=$(ls | grep -c *.htmlt)
+if [[ "$N" != "0" ]] ; then
+  ls *.htmlt | sed 's/\.htmlt//' | while read template ; do
+    clog INFO "Rendering $template.htmlt => $template.html"
+    $template.renderer $template.htmlt > $template.html
+    normal_exit $?
+  done
+  [[ $? != 0 ]] && exit $?
+fi
+
+N=$(ls | grep -c *.gt)
+if [[ "$N" != "0" ]] ; then
+  ls *.gt | sed 's/\.gt//' | while read template ; do
+    clog INFO "Rendering $template.gt => $template.md"
+    gtp $template.gt > $template.md
+    normal_exit $?
+  done
+  [[ $? != 0 ]] && exit $?
+fi
+
+# Set up a title page if needed
+TITLE_PAGE_ARG=
+if [[ "$TITLE_PAGE" != "" ]] ; then
+  TITLE_PAGE_ARG="$TITLE_PAGE"
+fi
+
+# Set up output file name
+OUTPUT_FILE_NAME_BASE_ARG=
+if [[ "$OUTPUT_FILE_NAME_BASE" != "" ]] ; then
+  OUTPUT_FILE_NAME_BASE_ARG="$OUTPUT_FILE_NAME_BASE"
+fi
+
+# Set up some variables based on FORMAT.
+TEMPLATE_ARG="--template $MKTECHDOCSHOME/lib/css_frame_template.html"
+PDF=false
+UML_FORMAT=svg
+case $FORMAT in
+  html)
+    TEMPLATE_ARG="--template $MKTECHDOCSHOME/lib/basic_template.html"
+  ;;
+  htmlsimple)
+    TEMPLATE_ARG=
+  ;;
+  pdf|pdffloat)
+    PDF=true
+    UML_FORMAT=eps
+  ;;
+esac
+
+# Setup the pandoc filter list with correct UML output format
+FILTERS="-F $MKTECHDOCSHOME/bin/flt-include.py -F $MKTECHDOCSHOME/bin/flt-comment-block.py -F $MKTECHDOCSHOME/bin/flt-comment.py -F $MKTECHDOCSHOME/bin/flt-plantuml.py -M umlformat=$UML_FORMAT -F $MKTECHDOCSHOME/bin/flt-notetip.py -F $MKTECHDOCSHOME/bin/flt-include-code.py"
+
+# Override that if the user specifies their own template
+if [[ "$CUSTOM_TEMPLATE" != "" ]] ; then
+  if [[ ! -r $CUSTOM_TEMPLATE ]] ; then
+    clog ERROR "Can't find custom template $CUSTOM_TEMPLATE. Giving up."
+    exit 1
+  fi
+
+  clog INFO "Setting up customized template"
+  TEMPLATE_ARG="--template $CUSTOM_TEMPLATE"
+fi
+
+# Remove and then create an output dir so we can put output files there
+clog INFO "Removing old ${OUTPUT_FILE_NAME_BASE_ARG}_pages (if it exists)"
+rm -rf ${OUTPUT_FILE_NAME_BASE_ARG}_pages
+normal_exit $?
+
+clog INFO "Creating ${OUTPUT_FILE_NAME_BASE_ARG}_pages for output"
+mkdir -p ${OUTPUT_FILE_NAME_BASE_ARG}_pages
+normal_exit $?
+
+# Set up style information
+if [[ "$TEMPLATE_ARG" == "" && "$HTML_STYLE" != "" ]] ; then
+  clog ERROR "Can't use styles with htmlsimple format."
+  exit 1
+fi
+
+HTML_STYLE_FILE=
+case $HTML_STYLE in
+  archwiki)
+    HTML_STYLE_FILE=$MKTECHDOCSHOME/lib/archwiki.css
+  ;;
+  github)
+    HTML_STYLE_FILE=$MKTECHDOCSHOME/lib/github.css
+  ;;
+  custom)
+    if [[ ! -r $CUSTOM_CSS ]] ; then
+      clog ERROR "When using custom css file, you must supply a readable file in CUSTOM_CSS."
+      exit 1
+    fi
+    HTML_STYLE_FILE=$CUSTOM_CSS
+  ;;
+  *)
+    clog ERROR "Don't understand HTML_STYLE value of $HTML_STYLE."
+    exit 1
+esac
+
+if [[ "$HTML_STYLE_FILE" != "" ]] ; then
+  cp -i $HTML_STYLE_FILE ${OUTPUT_FILE_NAME_BASE_ARG}_pages/mktechdocs.css
   normal_exit $?
-done
+fi
 
-clog INFO "Building main template index.pyt"
-pandoc -s --ascii --highlight-style tango -f markdown --wrap=preserve -f markdown -t html --template $MKTECHDOCSHOME/lib/css_frame_template.html -N -V numbersections=1 --toc --toc-depth=6 $FILTERS title-page.md mktechdocsiug.md > index.pyt
+# Set up table of contents
+TOC_ARG=
+if [[ "$TABLE_OF_CONTENTS_MAIN_DEPTH" != "" ]] ; then
+  TOC_ARG="--toc --toc-depth=$TABLE_OF_CONTENTS_MAIN_DEPTH"
+fi
+
+# This is for multihtml output, which isn't yet supported
+#TABLE_OF_CONTENTS_SUB_DEPTH=6
+
+# Set up section numbering
+SECTION_NUMBERS_ARG=
+if [[ "$SECTION_NUMBERS" == "true" ]] ; then
+  SECTION_NUMBERS_ARG="-V numbersections=1"
+fi
+
+if [[ "$PDF" == "true" ]] ; then
+  # PDF OUTPUT
+  pandoc $FILTERS -N --listings -H $TEXLISTINGS --template=$TEXTEMPLATE --latex-engine=xelatex -f markdown -t latex -V geometry:margin=1in -V mainfont="$PDF_MAIN_FONT" -V monofont="$PDF_MONO_FONT" $TOC_ARG $TITLE_PAGE_ARG master.md > $OUTPUT_FILE_NAME_BASE_ARG.tex
+  clog INFO "Fixing floating diagrams." 
+  sed -i "" 's/\\begin{figure}/\\begin{figure}\[H\]/g' $OUTPUT_FILE_NAME_BASE_ARG.tex
+  normal_exit $?
+  clog INFO "Creating pdf, pass 1"
+  xelatex -halt-on-error -interaction nonstopmode -output-directory . $OUTPUT_FILE_NAME_BASE_ARG.tex 1>xelatex1.out 2>&1
+  normal_exit $?
+  clog INFO "Creating pdf, pass 2"
+  xelatex -halt-on-error -interaction nonstopmode -output-directory . $OUTPUT_FILE_NAME_BASE_ARG.tex 1>xelatex2.out 2>&1
+  normal_exit $?
+  clog INFO "Creating pdf, pass 3"
+  xelatex -halt-on-error -interaction nonstopmode -output-directory . $OUTPUT_FILE_NAME_BASE_ARG.tex 1>xelatex3.out 2>&1
+  normal_exit $?
+  mv $OUTPUT_FILE_NAME_BASE_ARG.pdf ${OUTPUT_FILE_NAME_BASE_ARG}_pages/$OUTPUT_FILE_NAME_BASE_ARG.pdf 
+  normal_exit $?
+else
+  # HTML OUTPUT
+  clog INFO "Building main template $OUTPUT_FILE_NAME_BASE_ARG.pyt"
+  pandoc -s --ascii --highlight-style tango -f markdown -t html --wrap=preserve -N $TEMPLATE_ARG $SECTION_NUMBERS_ARG $TOC_ARG $FILTERS $TITLE_PAGE_ARG master.md > $OUTPUT_FILE_NAME_BASE_ARG.pyt
 normal_exit $?
 
-clog INFO "Fixing jinja brackets"
-escape-jinja-brackets.sh index.pyt
-normal_exit $?
+  clog INFO "Fixing jinja brackets"
+  escape-jinja-brackets.sh $OUTPUT_FILE_NAME_BASE_ARG.pyt
+  normal_exit $?
 
-clog INFO "Rendering index.html"
-page.renderer index.pyt > index.html
-normal_exit $?
+  clog INFO "Rendering $OUTPUT_FILE_NAME_BASE_ARG.html"
+  $MKTECHDOCSHOME/bin/page_renderer.py $OUTPUT_FILE_NAME_BASE_ARG.pyt > ${OUTPUT_FILE_NAME_BASE_ARG}_pages/$OUTPUT_FILE_NAME_BASE_ARG.html
+  normal_exit $?
 
-# Clean up all the temporary build files
+  clog INFO "Copying any necessary files to the output directory"
+  cp -f *.svg *.png ${OUTPUT_FILE_NAME_BASE_ARG}_pages/. 2>/dev/null
+  if [[ "$IMAGES" != "" ]] ; then
+    # TBD NEEDS TEST for existence
+    cp -r $IMAGES ${OUTPUT_FILE_NAME_BASE_ARG}_pages/.
+    normal_exit $?
+  fi
+fi
 
-ls *.pyt | sed 's/\.pyt//' | while read template ; do
-  clog INFO "Removing temporary file $template.md"
-  rm -f $template.md
-done
+# Run any post-build jobs
+if [[ "$BUILD_SCRIPT" != "" ]] ; then
+  if [[ -e $BUILD_SCRIPT ]] ; then
+    clog INFO "Running post-build job $BUILD_SCRIPT"
+    $BUILD_SCRIPT post
+  else
+    clog ERROR "$BUILD_SCRIPT is not executable. Giving up."
+    exit 1
+  fi
+fi
 
-ls *.htmlt | sed 's/\.htmlt//' | while read template ; do
-  clog INFO "Removing temporary file $template.html"
-  rm -f $template.html
-done
-
-clog INFO "removing temporary uml and index.pyt"
-rm -f *.uml index.pyt
+# Clean up old, possibly failed builds
+cleanup
 
 popd
 normal_exit $?
